"use strict";
const fullName = 'Lucas Yasumura';
const isCool = true;
const totalPets = 1;
const empty = null;
let nothing;
console.log('Full Name: ', fullName);
console.log('Is Cool: ', isCool);
console.log('Total Pets: ', totalPets);
console.log('typeof Full Name: ', typeof fullName);
console.log('typeof Is Cool: ', typeof isCool);
console.log('typeof Total Pets: ', typeof totalPets);
console.log('Empty: ', empty);
console.log('typeof Empty: ', typeof empty);
console.log('Nothing: ', nothing);
console.log('typeof Nothing: ', nothing);
