const width: number = 5;
const height: number = 10;
const area: number = width * height;
const bill: number = 1200;
const payment: number = 2000;
const change: number = payment - bill;
const quizzes: number = 89;
const midterm: number = 92;
const final: number = 100;
const grade: number = (quizzes + midterm + final) / 3;
const firstName: string = 'Lucas';
const lastName: string = 'Yasumura';
const fullName: string = firstName + ' ' + lastName;
const pH: number = 1;
const isAcidic: boolean = pH < 7;
const headCount: number = 170;
const isSparta: boolean = headCount === 300;
const motto: string = fullName + ' is the GOAT';
console.log('typeof Area: ', typeof area);
console.log('Change: ', change);
console.log('typeof Change: ', typeof change);
console.log('Grade: ', grade);
console.log('typeof Grade: ', typeof grade);
console.log('Full Name', fullName);
console.log('typeof Full Name: ', typeof fullName);
console.log('Is Acidic: ', pH < 7);
console.log('typeof Is Acidic: ', typeof isAcidic);
console.log('Is Sparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
console.log('Motto: ', motto);
console.log('typeof Motto: ', typeof motto);
