'use strict';
const width = 5;
const height = 10;
const area = width * height;
const bill = 1200;
const payment = 2000;
const change = payment - bill;
const quizzes = 89;
const midterm = 92;
const final = 100;
const grade = (quizzes + midterm + final) / 3;
const firstName = 'Lucas';
const lastName = 'Yasumura';
const fullName = firstName + ' ' + lastName;
const pH = 1;
const isAcidic = pH < 7;
const headCount = 170;
const isSparta = headCount == 300;
const motto = fullName + ' is the GOAT';
console.log('typeof Area: ', typeof area);
console.log('Change: ', change);
console.log('typeof Change: ', typeof change);
console.log('Grade: ', grade);
console.log('typeof Grade: ', typeof grade);
console.log('Full Name', fullName);
console.log('typeof Full Name: ', typeof fullName);
console.log('Is Acidic: ', pH < 7);
console.log('typeof Is Acidic: ', typeof isAcidic);
console.log('Is Sparta: ', headCount == 300);
console.log('typeof isSparta: ', typeof isSparta);
console.log('Motto: ', motto);
console.log('typeof Motto: ', typeof motto);
